### ISSUE TITLE
OIOSAML.NET vs OIOIDWS.NET vs Seal.net

### ISSUE THREAD

**Issue by mikkeljohnsen** [digst/OIOSAML.Net#10]
Er det nogen som kan forklare mig hvad forskellen er på de 3 biblioteker ?

Jeg kan slet ikke finde hoved og hale i hvad der skal/kan bruges hvor.

Jeg kan læse at OIOSAML.NET kan bruges med det nye MitId, betyder det så at det erstatter OIOIDWS.NET ?

**Comment by mdbech** [comment]
@mikkeljohnsen kort riset op så benyttes de pakker på følgende vis:
- OIO SAML: Integration med NemLog-ins IdP (bruger autentifikation / frontchannel)
- OIO IDWS: Integration med NemLog-ins STS (backchannel)
- Seal.NET: Integration med NSP (backchannel)

Du kan ikke benytte OIO SAML direkte til MitID, da det skal gå igennem en broker og MitID anvender iøvrigt OpenID Connect til autentifikation.

Du kan læse mere tingene her:
- OIO SAML: https://www.digitaliser.dk/group/42063
- OIO IDWS:  https://www.digitaliser.dk/group/705156
- Seal.NET: https://www.medcom.dk/standarder/webservice-standarder/den-gode-webservice
- MitID: https://digst.dk/it-loesninger/mitid/
