### ISSUE TITLE
Capturing group is not used

### ISSUE THREAD

**Issue by jesmsundheddk** [digst/OIOSAML.Net#29]
https://github.com/digst/OIOSAML.Net/blob/8df8d95bba197a991c566de8160d1d97c6bed3d4/src/dk.nita.saml20/dk.nita.saml20/Utils/BrowserSupportUtil.cs#L50

The capturing group for version, i.e. Match.Groups[1] and not the entire match should be used.

**Comment by mdbech** [comment]
Should be fixed with #61 .
